# -*- coding: utf-8 -*-
"""ventasoficial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HkeC2O3ItIifKlTOZfY1ZMoxWG59ytu

### SECCIÓN 1: CARGAR EL DATASET E IMPORTAR LIBRERÍAS
En esta parte inicial, prepararemos el entorno de trabajo instalando y llamando a las herramientas necesarias.
"""

import pandas as pd

try:
    import langchain
    print("Librería LangChain importada correctamente")
except ImportError:
    # Si no está instalada, mostramos cómo hacerlo
    print("Librería LangChain no detectada. Instalando...")
    !pip install langchain -q
    import langchain
    print("Librería LangChain importada correctamente")

print("Librería Pandas importada correctamente")

# Cargamos el archivo CSV que ya tienes en el entorno de Colab
# Usamos la función read_csv de pandas con una codificación estándar
try:
    df = pd.read_csv('/content/sales_data_sample.csv', encoding='unicode_escape')
    print("Archivo 'sales_data_sample.csv' cargado exitosamente en la variable 'df'")
except Exception as e:
    print(f"Error al cargar el archivo: {e}")

"""### SECCIÓN 2: NORMALIZACIÓN Y LIMPIEZA PASO A PASO
Ahora transformaremos los datos para que sean fáciles de procesar por cualquier modelo de IA.
"""

# 1. Normalizar nombres de columnas
# Convertimos todo a minúsculas y reemplazamos espacios por guiones bajos
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

print("Nombres de columnas normalizados:")
print(df.columns.tolist())

# 2. Verificar valores nulos
# Mostramos cuántos datos faltan en cada columna
print("Valores nulos por columna antes de la limpieza:")
display(df.isnull().sum())

# 3. Reemplazar valores nulos de forma didáctica

# Para columnas numéricas: llenamos con 0
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(0)

# Para columnas de texto (objetos): llenamos con 'No especificado'
text_cols = df.select_dtypes(include=['object']).columns
df[text_cols] = df[text_cols].fillna('No especificado')

print("Limpieza de nulos completada: los números vacíos ahora son 0 y los textos vacíos son 'No especificado'.")

# 4. Limpieza de caracteres especiales en columnas de texto
# Definimos una función simple para limpiar el texto
def limpiar_texto(texto):
    if isinstance(texto, str):
        # Ejemplo simple: quitar comillas dobles y caracteres raros comunes
        texto = texto.replace('"', '').replace("'", "")
        # Aquí podrías añadir más reemplazos según necesites
        return texto
    return texto

# Aplicamos la limpieza a todas las columnas de texto
for col in text_cols:
    df[col] = df[col].apply(limpiar_texto)

print("Caracteres especiales básicos han sido limpiados de las columnas de texto.")

# 5. Mostrar estructura final y estadísticas
print("--- Información del Dataset ---")
df.info()

print("\n--- Estadísticas Generales ---")
display(df.describe())

"""### SECCIÓN 3: GUARDAR EL RESULTADO
Finalmente, guardamos nuestro trabajo en un nuevo archivo limpio.
"""

# Exportamos el DataFrame a un nuevo archivo CSV
df.to_csv('ventasxime.csv', index=False)

print("¡El dataset ha sido normalizado y guardado con éxito como sales_data_cleaned.csv!")

"""### VERIFICACIÓN DEL ARCHIVO GENERADO
En esta celda cargaremos el nuevo archivo para comprobar que la limpieza se guardó correctamente.
"""

# 1. Cargamos el nuevo archivo generado
df_verificacion = pd.read_csv('ventasxime.csv')

# 2. Comprobamos si hay nulos (debería salir todo en 0)
print("Conteo de valores nulos en el nuevo archivo:")
print(df_verificacion.isnull().sum().sum())

# 3. Mostramos las primeras filas para validar visualmente la limpieza
print("\nVista previa de los datos normalizados y limpios:")
display(df_verificacion.head())

"""### CONFIGURACIÓN DEL AGENTE CON CONTEXTO DETALLADO
En este bloque inicializamos el modelo de lenguaje y configuramos el agente con el diccionario de columnas para asegurar la máxima precisión en sus respuestas.
"""

# 1. Instalación de librerías necesarias de forma silenciosa
!pip install langchain langchain-mistralai langchain-experimental pandas -q

import pandas as pd
from google.colab import userdata
from langchain_mistralai import ChatMistralAI
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent

# 2. Recuperación de la clave API desde los secretos de Colab
try:
    mistral_key = userdata.get('MISTRAL_API_KEY')
except Exception as e:
    print("❌ ERROR: No se pudo acceder a MISTRAL_API_KEY.")
    print("Por favor, ve al icono de la llave (Secrets) a la izquierda y activa el 'Notebook access' para MISTRAL_API_KEY.")
    mistral_key = None

if mistral_key:
    # 3. Inicialización del LLM (Mistral) con temperatura 0
    llm = ChatMistralAI(api_key=mistral_key, model="mistral-small-latest", temperature=0)

    # 4. Carga de los datos normalizados
    df = pd.read_csv('ventasxime.csv')

    # 5. Definición del Prompt con el diccionario de datos según la cátedra
    prefix_prompt = """
    Sos un analista de datos experto en ventas.
    Trabajás con un DataFrame llamado 'df' que tiene estas columnas:
    - ordernumber: número de orden
    - quantityordered: cantidad de productos pedidos
    - priceeach: precio unitario
    - sales: total de la venta
    - orderdate: fecha del pedido
    - status: estado del pedido (Shipped, Cancelled, Resolved, etc.)
    - qtr_id: id del trimestre
    - month_id: número de mes
    - year_id: año del pedido
    - productline: línea de producto (Motorcycles, Classic Cars, etc.)
    - customername: nombre del cliente
    - city: ciudad del cliente
    - country: país del cliente
    - dealsize: tamaño del deal (Small, Medium, Large)

    Instrucciones:
    1. Para resolver cualquier pregunta numérica, estadística o de filtros (como sumar ventas, promedios o buscar el año con mayores ventas), DEBES escribir y ejecutar código de Python con Pandas sobre el DataFrame 'df'.
    2. Responde siempre en español, de forma clara y concisa.
    3. Si no podés responder en base a los datos, decilo claramente.
    """

    # 6. Creación del agente de Pandas
    agent = create_pandas_dataframe_agent(
        llm,
        df,
        prefix=prefix_prompt,
        verbose=True,
        allow_dangerous_code=True,
        agent_type="tool-calling"
    )

    # 7. Confirmación final
    print("✓ Agente configurado con el contexto detallado del dataset.")

"""### PRUEBA DE CONSULTA DE NEGOCIO
Utilizamos el método invoke para que el agente analice los datos y determine el año con mejor desempeño comercial.
"""

# Definimos la consulta específica
query = "¿Cuál fue el año que mayor ventas (sales) tuvo?"

# Ejecutamos el agente y guardamos el resultado
respuesta = agent.invoke(query)

# Mostramos la conclusión final
print(f"\nResultado del análisis: {respuesta['output']}")

# Segunda prueba de consultas
# Definimos la consulta específica
query = "¿Cuales son los 3 países que generaron más ingresos totales?"

# Ejecutamos el agente y guardamos el resultado
respuesta = agent.invoke(query)

# Mostramos la conclusión final
print(f"\nResultado del análisis: {respuesta['output']}")

"""# CREACIÓN RAG"""

# 1. Instalación de librerías y reinicio automático para aplicar cambios de versión
import os

try:
    import opentelemetry.sdk.environment_variables
    from langchain_huggingface import HuggingFaceEmbeddings
    print("✓ Librerías verificadas y listas para usar.")
except (ImportError, ModuleNotFoundError):
    print("⚠ Instalando dependencias faltantes...")
    !pip install -U "opentelemetry-api>=1.24.0" "opentelemetry-sdk>=1.24.0" -q
    !pip install langchain langchain-mistralai langchain-chroma langchain-huggingface sentence-transformers chromadb pandas -q

    print("\n¡REINICIANDO ENTORNO PARA APLICAR CAMBIOS! Por favor, ejecuta esta celda una vez más.")
    os.kill(os.getpid(), 9)

import pandas as pd
from google.colab import userdata
from langchain_mistralai import ChatMistralAI
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# 2. PREPARACIÓN DE DOCUMENTOS (CORPUS)
# Cargamos el dataset normalizado
df_rag = pd.read_csv('ventasxime.csv')

# Función para transformar una fila en un texto descriptivo (narrativa)
def fila_a_texto(row):
    return (
        f"Orden: {row['ordernumber']}, Producto: {row['productline']}, "
        f"Cliente: {row['customername']}, Ventas: {row['sales']}, "
        f"Cantidad: {row['quantityordered']}, Precio Unitario: {row['priceeach']}, "
        f"Fecha: {row['orderdate']}, Estado: {row['status']}, "
        f"Ciudad: {row['city']}, Pais: {row['country']}, Tamaño: {row['dealsize']}."
    )

# Creamos la lista de objetos 'Document' de LangChain
documentos = [
    Document(page_content=fila_a_texto(row), metadata={"id": row['ordernumber']})
    for _, row in df_rag.iterrows()
]

print(f"✓ Se han procesado {len(documentos)} documentos para el corpus.")

# 3. BASE VECTORIAL CON CHROMADB
# Inicializamos el modelo de embeddings (gratuito y local)
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Creamos la base de datos vectorial en memoria
vectorstore = Chroma.from_documents(
    documents=documentos,
    embedding=embeddings,
    collection_name="ventas_xime"
)

# Configuramos el retriever para buscar los 5 documentos más parecidos (k=5)
retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

print("✓ Base vectorial ChromaDB creada correctamente.")

# 4. CONFIGURACIÓN DE LA CADENA RAG CON MISTRAL
# Recuperamos la clave API
mistral_key = userdata.get('MISTRAL_API_KEY')

# Inicializamos el LLM
llm_rag = ChatMistralAI(api_key=mistral_key, model="mistral-small-latest", temperature=0)

# 5. SYSTEM PROMPT DEL RAG
template = """
Sos un analista de datos experto en ventas y asistente de soporte RAG.
Tu tarea es responder las preguntas del usuario basándote ÚNICAMENTE en el contexto de los documentos recuperados que se te proporcionan.

Contexto de las columnas principales (en minúsculas):
ordernumber, quantityordered, priceeach, sales, orderdate, status, qtr_id, month_id, year_id, productline, customername, city, country, dealsize.

Instrucciones críticas:
- Responde siempre en español de forma clara, concisa y profesional.
- Basa tu respuesta estrictamente en los documentos del contexto.
- Si la respuesta no se puede deducir del contexto, di claramente: 'No cuento con información suficiente en el corpus para responder a esa pregunta'.

Contexto recuperado:
{context}

Pregunta del usuario:
{question}
"""

prompt_rag = ChatPromptTemplate.from_template(template)

# Construcción de la cadena usando LCEL (LangChain Expression Language)
rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt_rag
    | llm_rag
    | StrOutputParser()
)

print("✓ Cadena RAG configurada y lista.")

# 6. INTERFAZ DE CHAT INTERACTIVO
print("--- Chat de Soporte de Ventas RAG Activo ---")
print("(Escribe 'salir' para finalizar)\n")

while True:
    usuario_input = input("Tu pregunta sobre ventas: ")

    if usuario_input.lower() == 'salir':
        print("Finalizando sesión de chat. ¡Hasta luego!")
        break

    if usuario_input.strip() == "":
        continue

    # Procesar la consulta a través de la cadena RAG
    try:
        respuesta_rag = rag_chain.invoke(usuario_input)
        print(f"\nAsistente RAG: {respuesta_rag}")
    except Exception as e:
        print(f"\nOcurrió un error al procesar la consulta: {e}")

    print("\n" + "-"*30)
    print("¿Quieres preguntarme algo más?")